// <auto-generated />
using Challenge.Ibge.Blazor.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Challenge.Ibge.Blazor.Infra.Data.Migrations
{
    [DbContext(typeof(IbgeDbContext))]
    [Migration("20231216064504_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Challenge.Ibge.Blazor.Infra.Data.Entities.IbgeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("CHAR(7)")
                        .HasColumnName("Id");

                    b.Property<string>("City")
                        .HasColumnType("NVARCHAR(80)")
                        .HasColumnName("City");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("CHAR(2)")
                        .HasColumnName("State");

                    b.HasKey("Id");

                    b.ToTable("IBGE", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
